from app.knowledge.testing_expert.schema import card

CARDS = [
    card("playwright", "Playwright 自动化", "automation",
         ["Playwright", "trace", "locator", "auto-wait"],
         "Web UI 自动化、需要稳定定位、追踪失败时",
         "Playwright 用自动等待、定位器、trace/screenshot/video 降低 UI 不稳定。优先 role/label/test-id，避免脆弱 CSS/XPath。适合现代 Web，不是所有层的唯一工具。",
         ["用 getByRole/getByTestId", "失败必留 trace 和截图", "网络拦截做前置数据", "等待用locator状态而不是固定sleep"],
         ["全文 sleep", "用绝对XPath", "一条E2E脚本覆盖全部规则"],
         ["Playwright 官方文档", "Microsoft Playwright best practices"]),
    card("selenium-cypress-appium", "Selenium / Cypress / Appium", "automation",
         ["Selenium", "Cypress", "Appium", "移动端自动化"],
         "选择或维护不同自动化技术栈时",
         "Selenium 生态广、跨语言；Cypress 对前端开发调试友好但跨域/多页签有约束；Appium 覆盖原生/混合 App。选工具看被测端和团队技能，而不是追新。",
         ["Web优先评估Playwright/Cypress", "原生App用Appium或厂商方案", "不要在一层工具里解决所有测试问题"],
         ["用Appium跑纯接口", "把历史Selenium脚本全量无评估重写"],
         ["Selenium 官方文档", "Cypress 官方文档", "Appium 官方文档"]),
    card("pom-screenplay", "Page Object 与 Screenplay", "automation",
         ["Page Object", "POM", "Screenplay", "页面对象"],
         "UI脚本开始重复、页面一改大面积失败时",
         "Page Object 把页面交互收口；Screenplay 用角色/任务/问题表达意图，适合复杂业务流程。目标是降低定位变更成本和提升可读性。",
         ["页面变更只改一处", "用例层写业务意图", "不要在PO里写业务断言大杂烩"],
         ["PO变成上帝类", "用例里仍到处写selector"],
         ["ISTQB Test Automation Engineer", "Selenium 官方文档"]),
    card("fixture-hook", "Fixture 与 Hook", "automation",
         ["fixture", "hook", "setup", "teardown", "beforeEach"],
         "需要稳定前置数据、隔离用例或清理环境时",
         "Fixture/Hook 管理准备和清理。好的隔离让用例可并行、可单跑。共享可变状态是 flaky 的常见根因。",
         ["每条用例独立账号或可回滚数据", "失败也要清理", "昂贵准备用作用域明确的fixture"],
         ["全局可变单例被并行用例互踩", "不清理导致下次误报"],
         ["Playwright 官方文档", "ISTQB Test Automation Engineer"]),
    card("assertion-wait-retry", "断言、等待与重试", "automation",
         ["assertion", "断言", "等待策略", "重试策略", "timeout"],
         "UI不稳定、偶发失败或要判断等的是产品还是脚本时",
         "等待应对齐可观察状态：元素可见、网络空闲、接口返回。重试可掩盖产品竞态，只能用于已知抖动并要报警。断言必须稳定且表达业务含义。",
         ["等待条件，不盲等时间", "重试次数和原因写进报告", "关键金额/权限断言不可被重试吞掉"],
         ["失败就自动重试三次当修复", "assert True 没有业务含义"],
         ["Playwright 官方文档", "Google Testing Blog"]),
    card("test-double", "Mock / Stub / Spy / Test Double", "automation",
         ["mock", "stub", "spy", "test double", "测试替身"],
         "依赖不可控、要隔离被测对象或制造异常时",
         "Stub 给固定答案；Mock 还验证交互；Spy 记录真实对象调用。接口测试里常用替身隔离支付、短信、第三方。系统测试要明确哪些用真依赖。",
         ["第三方超时/5xx用stub制造", "契约仍要有真实依赖抽样", "替身与真实行为偏差要评审"],
         ["全链路都mock后还宣称E2E通过", "mock过期导致假绿"],
         ["ISTQB CTFL 4.x", "ISTQB Test Automation Engineer"]),
    card("auth-session", "认证鉴权与会话", "api",
         ["认证", "授权", "鉴权", "接口鉴权", "cookie", "session", "token", "jwt", "oauth", "登录态"],
         "测登录、权限、接口安全或会话过期时",
         "认证回答你是谁，授权回答你能做什么。Cookie/Session 与 JWT/OAuth 失败模式不同：过期、伪造、刷新、越权、退出后残留。必须同时测前端路由和后端接口。",
         ["退出后旧token应失效", "水平越权：改id访问他人数据", "垂直越权：普通用户打管理接口", "刷新令牌与过期窗口"],
         ["只测页面跳转不测接口", "认为前端隐藏按钮等于无权限"],
         ["ISTQB Security Testing", "OWASP Top 10"]),
    card("locator-iframe-shadow", "定位、iframe、Shadow DOM、多窗口", "automation",
         ["元素定位", "iframe", "shadow dom", "多窗口", "弹窗", "dialog"],
         "页面有嵌套框架、组件封装、弹窗或新窗口时",
         "先进入正确的frame/shadow root再定位。弹窗分页面内dialog、window.alert、新tab。文件选择、权限提示也要单独策略。",
         ["明确frame层级", "新窗口等待popup事件", "原生alert与自定义弹层分开处理"],
         ["在主文档找iframe里的按钮", "忽略shadow边界"],
         ["Playwright 官方文档"]),
    card("upload-download-network", "上传下载与网络拦截", "automation",
         ["文件上传", "文件下载", "网络拦截", "websocket", "sse"],
         "测文件、弱网、实时推送或要注入接口失败时",
         "上传要覆盖类型、大小、病毒/脚本文件、中断。下载要校验文件内容和权限。网络拦截可模拟500、超时、慢网。WebSocket/SSE要测重连和乱序。",
         ["后端再校验一次文件", "下载鉴权不可只靠前端链接", "用拦截制造接口失败看UI恢复"],
         ["只测选择文件成功", "不校验下载文件内容"],
         ["Playwright 官方文档", "OWASP"]),
    card("isolation-parallel-flaky", "隔离、并行与Flaky", "automation",
         ["测试隔离", "测试并行", "稳定性", "flaky", "flaky test"],
         "CI变绿又变红、并行互踩或定位偶发失败时",
         "Flaky 来自等待、数据竞争、时间、依赖抖动、顺序依赖。先隔离再并行。修flaky优先于加新用例。",
         ["单测可单独跑", "并行用独立数据", "对flaky建档案：频率、环境、根因"],
         ["忽略偶发失败", "用重试当稳定性策略"],
         ["Google Testing Blog", "Playwright 官方文档"]),
    card("ci-report-trace", "CI执行与失败诊断", "automation",
         ["CI执行", "测试报告", "trace", "screenshot", "video", "日志", "失败诊断"],
         "流水线失败或需要判断产品缺陷还是脚本问题时",
         "CI里每次失败都应留下日志、截图、trace/video和接口响应。诊断顺序：环境 → 数据 → 脚本等待/定位 → 产品行为。",
         ["产物归档到构建", "失败分类后再提单", "同一flaky不要连续报多个重复缺陷"],
         ["只有“timeout”三个字", "不看trace就改脚本"],
         ["ISTQB Test Automation Engineer", "Playwright 官方文档"]),
    card("http-rest-graphql", "HTTP / REST / GraphQL", "api",
         ["http", "https", "rest", "graphql", "状态码", "header", "json", "xml", "schema"],
         "设计或执行接口测试时",
         "接口测试看契约：方法、路径、鉴权、参数、状态码、响应schema、幂等、错误模型。GraphQL还要测查询深度和字段权限。",
         ["2xx/4xx/5xx都要有用例", "校验必填、类型、枚举", "错误信息不泄露堆栈", "HTTPS证书和重定向"],
         ["只断言200", "不校验响应字段类型"],
         ["ISTQB", "REST API testing实践", "Postman / Newman"]),
    card("api-chaining", "接口链路与依赖", "api",
         ["api chaining", "接口依赖", "接口链路", "编排"],
         "一个业务要跨多个接口才能完成时",
         "链路测试按业务顺序串联，并校验中间状态和最终数据。要能在任一步失败后断言补偿/回滚，而不是只看最后成功。",
         ["下单=锁库存+生成订单+支付意图", "失败步骤后查数据库和后续接口", "用可追踪的业务id串联日志"],
         ["每步都200就当业务成功", "链路数据不可重复执行"],
         ["Postman / Newman", "ISTQB Test Automation Engineer"]),
    card("api-quality", "幂等、分页、限流、超时重试", "api",
         ["幂等", "分页", "排序", "过滤", "限流", "并发", "超时", "重试", "缓存"],
         "写操作、列表接口或高并发接口测试时",
         "写操作要测重复提交是否重复生效。分页要测页码边界、总数、排序稳定性。限流、超时、重试会影响用户感知和数据一致性。",
         ["支付/创建用同一idempotency key重放", "最后一页、空页、超大pageSize", "超时后重试是否重复下单"],
         ["列表只测第一页", "忽略缓存导致读到旧权限"],
         ["ISTQB", "REST API testing实践"]),
    card("db-testing", "数据库测试", "database",
         ["sql", "crud", "join", "事务", "索引", "约束", "一致性", "回滚", "锁", "数据清理"],
         "接口成功但数据不对，或要构造/清理测试数据时",
         "数据库测试验证持久化：约束、事务、并发、回滚、前后端一致。接口200不等于数据正确。测试数据必须可构造可清理。",
         ["写后读库核对", "唯一约束冲突", "事务中失败应回滚", "并发更新用版本号/锁"],
         ["只看接口JSON", "测试后不清理污染环境"],
         ["ISTQB Advanced Technical Test Analyst"]),
    card("performance", "性能测试基础", "performance",
         ["性能测试", "load", "stress", "spike", "endurance", "tps", "qps", "rt", "p95", "p99", "瓶颈", "性能基线"],
         "要验证容量、响应时间或版本性能回归时",
         "先定义负载模型和SLO：P95/P99、TPS、错误率。Load看目标容量，Stress找崩溃点，Spike看突发，Endurance看泄漏。没有基线就没有回归。",
         ["用生产画像建模", "看CPU/内存/IO/数据库慢查询", "性能回归对比基线而不是感觉"],
         ["用UI自动化当压测", "只报平均响应时间"],
         ["ISTQB Performance Testing"]),
    card("security", "安全测试基础", "security",
         ["安全测试", "sql注入", "xss", "csrf", "ssrf", "越权", "owasp", "敏感信息"],
         "有输入、上传、鉴权、回调或管理后台时",
         "安全测试至少覆盖认证授权、注入、XSS、CSRF、SSRF、上传、敏感信息、会话。OWASP Top 10 是风险清单，不是勾选游戏。发现安全问题默认高严重级别。",
         ["所有输入当不可信", "水平/垂直越权必测", "上传限制类型和内容", "日志和接口不回显密钥"],
         ["只靠WAF就认为安全", "在生产用破坏性PoC"],
         ["ISTQB Security Testing", "OWASP Top 10"]),
    card("agile-shift", "Agile / 左移 / 右移 / 持续测试", "agile",
         ["agile", "敏捷测试", "shift-left", "shift-right", "持续测试", "devops", "ci/cd"],
         "迭代短、发布频繁或质量门禁要进流水线时",
         "左移：评审、单测、契约、静态分析尽早发现。右移：生产监控、金丝雀、真实用户问题回流。持续测试把合适的自动化嵌进CI/CD，而不是把所有测试塞进流水线。",
         ["PR门禁用快且稳的检查", "夜间跑慢速/全量", "线上缺陷回流成回归"],
         ["敏捷=不写用例", "流水线被E2E拖垮"],
         ["ISTQB Agile Tester", "DevOps Testing实践"]),
    card("tester-thinking", "测试人员思维", "thinking",
         ["测试思维", "测试人员脑子", "不要无脑生成用例", "风险选择"],
         "用户只说“帮我测XX”或需求只有一句话时",
         "优秀测试人员先想风险和用户伤害，再选技术，再决定测哪些。不是把能想到的全写成用例。要问正常、异常、边界、权限、会话、并发、兼容，再按风险裁剪。",
         ["先列风险再选题", "P0必须能发布阻断", "把“不测”写出来并说明原因", "结合当前项目已有资产增量测"],
         ["无脑生成几十条重复用例", "只覆盖用户原话"],
         ["ISTQB Advanced Test Analyst", "ISTQB CTFL 4.x"]),
]
